env:
    - USER=travis

sudo: false

language: go

go:
  - 1.9

before_script:
    - make vet

install:
  - make deps

script:
  - GOMAXPROCS=2 make ci

branches:
  only:
    - master

matrix:
  fast_finish: true
